version: '3.8'

name: contract-generator-infra

services:
  mongodb:
    container_name: contract-generator-mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - contract-generator-network

networks:
  contract-generator-network:
    driver: bridge

